### PR TITLE
Implementing the Twitter endpoints

### PR DESCRIPTION
**Pull request by The24thDS**
- Rewrote the classic function into a fat arrow function
- Grouped the code a little bit
- Tested: Twitter is responding with complains about the callback URL not being approved. Probably something has to be approved by @sahil-rajput

### CODE REVIEW

**Comment by The24thDS** [comment]
This is still in progress, I will implemented the second one tomorrow and then we'll merge the PR :)

**Comment by The24thDS** [comment]
I've merged the branch I used for deploying to Heroku. It contains the second endpoint used in the Twitter authentication. I was unable to test it because the callback URL is not authorized yet.

**Comment by kriyeng** [comment]
The changes looks very good for me @The24thDS! I think we can merge and wait for @sahil-rajput to add the same URL callback to twitter development platform. We can always open a new issue if we detect something when we'll be able to test.

**Comment by The24thDS** [comment]
So, this is resolving #6

**Pull request merged**
